#
# Python 3 Titus travis.yml config file
#
# YAML Validator:   http://lint.travis-ci.org/
#

language: python
python:
  - "3.7"
  
# command to install dependencies
install:
  - pip install avro-python3
  - pip install ply
  - pip install pyyaml
  - pip install numpy
  - pip install pytz
  - pip install codecov
  
# command to run tests
script:
  - python -c "import sys; print(sys.platform)"
  - coverage run setup.py test

# Push the results back to codecov
after_success:
  - codecov
